### ISSUE TITLE
feat: handle pre-releases

### ISSUE THREAD

**Issue by cafkafk** [cafkafk/rime#11]
Currently, we just get the latest release, without considering whether or not it's a pre-release. I think we should default to avoiding pre-releases, and instead create some sort of `semi-unstable` endpoint that gets these as well.

**Comment by algernon** [comment]
Rather than a separate endpoint, how about a query param to the project endpoint? `/api/v1/github/user/repo.tar.gz?pre-releases=true`?

**Comment by cafkafk** [comment]
I'm not sure if we can actually do query parameters after the `.tar.gz`, although if we can that's cool.

**Comment by algernon** [comment]
> I'm not sure if we can actually do query parameters after the `.tar.gz`, although if we can that's cool.

`nix run` has no problem with it, and Axum can work with them too, it's just another extractor. The routes don't even need to change, it's the endpoints where it's all at.

**Comment by cafkafk** [comment]
I thought for some reason that `nix run` wouldn't work with it >_< 

...It's very good news it does, that allows us to do a lot of cool things

**Comment by algernon** [comment]
Quick question: how much effort should Rime put into finding a version that isn't a pre-release? As in, if there isn't a proper release on the first page, should it try the next page?

I'm inclined to go for simplicity, and try the first page only. That's still ~100 releases afteralll, if we set the max. Heck, I'd even go a step further, and request only the default (30 for GitHub, 20 for GitLab, 50 for Forgejo), or a reasonable default (say, 42, because I like that number).

The higher page size, the higher the traffic between Rime and the forge, and thus, the slower it gets, too. Maybe this should be configurable, with a reasonable default.

**Comment by algernon** [comment]
Just checked: GitHub and GitLab do not support filtering out prereleases on the API level, Forgejo does, so we can be a bit more efficient there.

**Comment by cafkafk** [comment]
> Quick question: how much effort should Rime put into finding a version that isn't a pre-release? As in, if there isn't a proper release on the first page, should it try the next page?
> 
> I'm inclined to go for simplicity, and try the first page only. That's still ~100 releases afteralll, if we set the max. Heck, I'd even go a step further, and request only the default (30 for GitHub, 20 for GitLab, 50 for Forgejo), or a reasonable default (say, 42, because I like that number).
> 
> The higher page size, the higher the traffic between Rime and the forge, and thus, the slower it gets, too. Maybe this should be configurable, with a reasonable default.

I think I had the (potentially bad idea) of going for the bare minimum, and then doubling that until we found it (like tcp sliding window scaling or smth :woman_shrugging:). Could have a query parameter that specifies the max wanted depth, because there is some value in getting a pre release if e.g. there have been many of those, and the last "release" was several years ago.

I'd probably use such a limit, but I'm not sure if we should default to it. Then again, we certainly need some default limit, and 42 sounds reasonable (although a lower limit might be more reasonable tbh, perhaps 10).

**Comment by cafkafk** [comment]
There also is a question of whether or not, and if so how we should communicate this to the user. It might make sense to give an error message telling them that there was no proper release, in a sense not failing silently and going with a pre-release, we might also inform them what query parameters might fix it for them.

**Comment by algernon** [comment]
OH, fun. Looks like GitLab does not support prereleases at all! But GitHub and Forgejo has a similar enough response that we can handle them the same way.

I'll have some PoC code to show in a bit.

**Comment by algernon** [comment]
> I think I had the (potentially bad idea) of going for the bare minimum, and then doubling that until we found it (like tcp sliding window scaling or smth 🤷‍♀️). 

I considered that, and it would be more efficient in the case where the latest release is a real release. If it isn't, I think the additional HTTP requests would be more wasteful than just grabbing a dozen or so releases in the first place.

Of course, if we start with, say 10 items per page, then 20, then 40... that might work. But the problem with *that* is doing so would include the first 10/20/40 too, so might aswell just request the next page instead of doubling, and achieve the same result with less traffic. None of the forge APIs support queries like "start with item 10, then get me 20 more", they're all "give me N items, page X", where all previous pages are assumed to have N items too.

In short, I think the sliding window idea is neat on paper, but not practically implementable, because the forges lack the API that'd let us do it.

> Could have a query parameter that specifies the max wanted depth, because there is some value in getting a pre release if e.g. there have been many of those, and the last "release" was several years ago.

Yeah, this makes sense.

> I'd probably use such a limit, but I'm not sure if we should default to it. Then again, we certainly need some default limit, and 42 sounds reasonable (although a lower limit might be more reasonable tbh, perhaps 10).

(I only mentioned 42, because it is the [The Answer to the Ultimate Question of Life, the Universe, and Everything](https://en.wikipedia.org/wiki/42_(number)#The_Hitchhiker's_Guide_to_the_Galaxy) O:))

**Comment by cafkafk** [comment]
> (I only mentioned 42, because it is the [The Answer to the Ultimate Question of Life, the Universe, and Everything](https://en.wikipedia.org/wiki/42_(number)#The_Hitchhiker's_Guide_to_the_Galaxy) O:))

Don't worry, I always keep a towel and a guide close by when doing any kind of software stuff.
