### ISSUE TITLE
bug: we can't deal with branches with slashes `/`

### ISSUE THREAD

**Issue by cafkafk** [cafkafk/rime#19]
Discovered in #18, honestly not something I'm personally super interested in trying to solve, but here's an issue so we don't forget.

**Comment by algernon** [comment]
```
❯ curl -i 'http://127.0.0.1:3000/v1/forgejo/git.madhouse-project.org/algernon/riemann-c-client/b/test%2fbranch.tar.gz' 
HTTP/1.1 303 See Other
location: https://git.madhouse-project.org/algernon/riemann-c-client/archive/test/branch.tar.gz
content-length: 0
date: Mon, 30 Oct 2023 19:24:42 GMT
```

Just need to url encode! :)

But we can do better: just replace `/:branch` in the routes with `/*branch`, so it captures the rest of the path. Since branch is *always* at the end, I believe this can be done safely. It will only captures paths, not query strings. Since the `/b/` or `/branch/` part of the URI will route the request there, we won't have problems accidentally routing the request elsewhere, either.
